import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'injection.config.dart';

/// Global instance of GetIt for dependency injection.
final getIt = GetIt.instance;

/// Configures all dependencies for LSP Application layer.
///
/// This function should be called in main.dart before the app starts:
///
/// ```dart
/// void main() async {
///   await configureLspApplicationDependencies();
///   runApp(MyApp());
/// }
/// ```
///
/// The configuration is generated by injectable_generator.
/// Run `dart run build_runner build` to generate injection.config.dart.
@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: true,
)
Future<void> configureLspApplicationDependencies() async {
  await getIt.init();
}
